# Generated by Django 3.0.5 on 2020-09-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, unique=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Grades')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(unique=True)),
                ('note', models.TextField(unique=True)),
                ('date', models.CharField(max_length=10)),
                ('student_id', models.IntegerField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos_URL', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('the_id_number', models.IntegerField(default=11111111, unique=True, verbose_name='the_id_number')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('grades', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Grades')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
